# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170712_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date'),
        ),
        migrations.AlterField(
            model_name='statusforclient',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date'),
        ),
        migrations.AlterField(
            model_name='statusforclientinfo',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date'),
        ),
        migrations.AlterField(
            model_name='statusforcontractor',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date'),
        ),
        migrations.AlterField(
            model_name='statusforcontractorinfo',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_column='creation_date'),
        ),
    ]
