# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20170713_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.UUIDField(db_column='id', primary_key=True, serialize=False)),
                ('version', models.UUIDField(db_column='version')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('name', models.CharField(db_column='name', max_length=100, verbose_name='наименование')),
                ('is_closed', models.BooleanField(db_column='is_closed', verbose_name='это закрывающий задачу статус')),
                ('contractor', models.ForeignKey(db_column='contractor', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
            ],
            options={
                'verbose_name_plural': 'статусы задач',
                'verbose_name': 'статус задачи',
                'db_table': 'task_status',
            },
        ),
        migrations.CreateModel(
            name='TaskStatusInfo',
            fields=[
                ('id', models.UUIDField(db_column='id', primary_key=True, serialize=False)),
                ('version', models.UUIDField(db_column='version')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.CASCADE, to='app.TaskStatus', verbose_name='статус')),
                ('task', models.ForeignKey(db_column='task', on_delete=django.db.models.deletion.CASCADE, to='app.Task', verbose_name='задача')),
            ],
            options={
                'verbose_name_plural': 'строки истории статусов задач',
                'verbose_name': 'строка истории статусов задачи',
                'db_table': 'task_status_info',
            },
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='task',
            field=models.ForeignKey(db_column='task', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Task', verbose_name='задача'),
        ),
    ]
