# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170713_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectStatusForClientInfo',
            new_name='ProjectStatusInfoForClient',
        ),
        migrations.RenameModel(
            old_name='ProjectStatusForContractorInfo',
            new_name='ProjectStatusInfoForContractor',
        ),
        migrations.AddField(
            model_name='project',
            name='status_date_for_client',
            field=models.DateTimeField(db_column='status_date_for_client', null=True, verbose_name='дата статуса, установленного заказчиком'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_date_for_contractor',
            field=models.DateTimeField(db_column='status_date_for_contractor', null=True, verbose_name='дата статуса, установленного исполнителем'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_for_client',
            field=models.ForeignKey(db_column='status_for_client', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProjectStatusForClient', verbose_name='статус, установленный заказчиком'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_for_contractor',
            field=models.ForeignKey(db_column='status_for_contractor', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProjectStatusForContractor', verbose_name='статус, установленный исполнителем'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(db_column='status', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TaskStatus', verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_date',
            field=models.DateTimeField(db_column='status_date', null=True, verbose_name='дата статуса'),
        ),
        migrations.AlterModelTable(
            name='projectstatusinfoforclient',
            table='project_status_info_for_client',
        ),
        migrations.AlterModelTable(
            name='projectstatusinfoforcontractor',
            table='project_status_info_for_contractor',
        ),
    ]
