# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170713_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='id',
            field=models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectstatusforclient',
            name='id',
            field=models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectstatusforcontractor',
            name='id',
            field=models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectstatusinfoforclient',
            name='id',
            field=models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectstatusinfoforcontractor',
            name='id',
            field=models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='id',
            field=models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskstatusinfo',
            name='id',
            field=models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False),
        ),
    ]
