# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20170722_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskWork',
            fields=[
                ('id', models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False)),
                ('version', models.UUIDField(db_column='version')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('date', models.DateField(db_column='date', verbose_name='дата работ')),
                ('work', models.PositiveIntegerField(db_column='work', verbose_name='количество часов')),
                ('comment', models.TextField(db_column='comment', verbose_name='комментарий')),
                ('task', models.ForeignKey(db_column='task', on_delete=django.db.models.deletion.CASCADE, to='app.Task', verbose_name='задача')),
            ],
            options={
                'verbose_name_plural': 'работы по задачам',
                'verbose_name': 'работы по задаче',
                'db_table': 'task_work',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.CharField(db_column='id', max_length=36, primary_key=True, serialize=False)),
                ('version', models.UUIDField(db_column='version')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('new_project_status_for_client', models.ForeignKey(db_column='new_project_status_for_client', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProjectStatusForClient', verbose_name='статус нового проекта для заказчика')),
                ('new_project_status_for_contractor', models.ForeignKey(db_column='new_project_status_for_contractor', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProjectStatusForContractor', verbose_name='статус нового проекта для исполнителя')),
                ('new_task_status', models.ForeignKey(db_column='new_task_status', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TaskStatus', verbose_name='статус новой задачи')),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name_plural': 'настройки пользователей',
                'verbose_name': 'настройка пользователя',
                'db_table': 'user_setting',
            },
        ),
    ]
