# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_auto_20170722_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=False, verbose_name='это действующий договор'),
        ),
        migrations.RemoveField(
            model_name='contract',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set([('client', 'contractor')]),
        ),
    ]
