# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20170726_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='author',
            field=models.ForeignKey(db_column='author', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='инициатор'),
            preserve_default=False,
        ),
    ]
